# 開発環境用 Docker Compose 設定
services:
  # 開発環境用アプリケーション
  app-dev:
    build: .
    container_name: news-assistant-dev
    command: uvicorn news_assistant.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./src/news_assistant:/app/news_assistant
      - ./data:/app/data
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
    environment:
      - NEWS_ASSISTANT_DB_URL=sqlite:///./data/news.db
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION:-japaneast}
      - SPEECH_PROVIDER=${SPEECH_PROVIDER:-azure}
      - OPENAI_TTS_MODEL=${OPENAI_TTS_MODEL:-tts-1}
      - OPENAI_TTS_VOICE=${OPENAI_TTS_VOICE:-alloy}
      - OPENAI_TTS_SPEED=${OPENAI_TTS_SPEED:-1.0}
      - ENVIRONMENT=development
    restart: unless-stopped

  # テスト実行用
  test:
    build: .
    command: sh -c "PYTHONPATH=/app pytest"
    volumes:
      - ./src/news_assistant:/app/news_assistant
      - ./tests:/app/tests
      - ./data:/app/data
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    environment:
      - NEWS_ASSISTANT_DB_URL=sqlite:///./data/news.db
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION:-japaneast}
      - SPEECH_PROVIDER=${SPEECH_PROVIDER:-azure}
      - OPENAI_TTS_MODEL=${OPENAI_TTS_MODEL:-tts-1}
      - OPENAI_TTS_VOICE=${OPENAI_TTS_VOICE:-alloy}
      - OPENAI_TTS_SPEED=${OPENAI_TTS_SPEED:-1.0}
      - ENVIRONMENT=testing

  # Poetry管理用
  poetry:
    build: .
    container_name: news-assistant-poetry
    command: poetry shell
    tty: true
    stdin_open: true
    volumes:
      - ./src/news_assistant:/app/news_assistant
      - ./tests:/app/tests
      - ./data:/app/data
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    environment:
      - NEWS_ASSISTANT_DB_URL=sqlite:///./data/news.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION:-japaneast}
      - SPEECH_PROVIDER=${SPEECH_PROVIDER:-azure}
      - OPENAI_TTS_MODEL=${OPENAI_TTS_MODEL:-tts-1}
      - OPENAI_TTS_VOICE=${OPENAI_TTS_VOICE:-alloy}
      - OPENAI_TTS_SPEED=${OPENAI_TTS_SPEED:-1.0}
      - ENVIRONMENT=development

volumes:
  data: 