"""Initial migration

Revision ID: 8e4d929bf314
Revises:
Create Date: 2025-05-25 03:06:42.498786

"""


# revision identifiers, used by Alembic.
revision = '8e4d929bf314'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
